# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20170521_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='new_title',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='message',
            new_name='topic_message',
        ),
    ]
