# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20170521_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='add_new_comment',
            new_name='message',
        ),
    ]
