# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20170521_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='author',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='stamp_created',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='stamp_updated',
        ),
    ]
