# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.Block')),
                ('link', models.FileField(upload_to='')),
            ],
            bases=('courses.block',),
        ),
        migrations.RenameModel(
            old_name='Multimedia',
            new_name='ImageBlock',
        ),
        migrations.RenameField(
            model_name='imageblock',
            old_name='link',
            new_name='image',
        ),
    ]
